Add : pin list 가져오기
wecode-bootcamp-korea/justcode-5-2nd-jjimterest-back pull request #7
Opened 2022-07-12 11:44 UTC by azure928

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [] 레이아웃 구현
- [x] 기능 추가
- [] 리뷰 반영
- [] 리팩토링
- [] 버그 수정
- [] 컨벤션 수정
- [] 초기 세팅

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- 
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

- pins 테이블에서 pin 리스트 전체를 select 하는데 created_at 순서로 정렬

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

-

<br />

## :: 기타 질문 및 특이 사항

- 아직 승인 안해주셔도 됩니다. 승인 필요하면 피어 리뷰 요청 라벨 붙여놓겠습니다.

2022-07-12 12:45 UTC, lshyun955 requested changes
코멘트 부분만 수정하시면 될 것 같습니다!!
고생하셨습니다!

2022-07-12 12:45 UTC, lshyun955 commented on routes/pins.js
> +//router.use(isLogin);
주석부분 필요 없으시면 지우셔도 될 것 같습니다!

2022-07-12 12:45 UTC, lshyun955 commented on server.js
> +///////////////////////////////
이 부분도 지워주셔도 될 것 같아요!

2022-07-12 12:47 UTC, azure928 commented on routes/pins.js
> +//router.use(isLogin);
코멘트 감사합니다! 반영 했습니다 😀

2022-07-12 12:48 UTC, lshyun955 approved these changes

2022-07-13 04:24 UTC, Jun0903 approved these changes
고생하셨어요!!

2022-07-13 04:34 UTC, merged